### ISSUE TITLE
resq not loaded

### ISSUE THREAD

**Issue by jessetabak** [abhinaba-ghosh/cypress-react-selector#114]
I get the following error:
```
[cypress-react-selector] not loaded yet. did you forget to run cy.waitForReact()?
```

It looks like window.resq is undefined.

![image](https://user-images.githubusercontent.com/5311393/102253306-724e7f00-3f07-11eb-92d3-1c9e85fcf3a3.png)

home.spec.js:
```js
describe('The Home Page', () => {
    before(() => {
        cy.visit('/');
        cy.waitForReact();
    });

    it('shows the header', () => {
        cy.react('Header')
            .should('be', 'visible');
        // .should('have.length', 1);
    });
});
```

cypress.json:
```json
{
    "baseUrl": "http://localhost:3000",
    "env": {
        "cypress-react-selector": {
            "root": "#root"
        }
    }
}
```

support/index.js:
```js
import './commands';
import 'cypress-react-selector';
```

**Comment by abhinaba-ghosh** [comment]
Hi @jessetabak , thanks for reporting this. In the above screenshot, can you also include the `before` section. Just want to check if `cypress-react-selector` loaded in the `before` hook.

**Comment by jessetabak** [comment]
@abhinaba-ghosh  There you go, seems like its loaded:

![image](https://user-images.githubusercontent.com/5311393/102333047-2a723b00-3f8d-11eb-8646-2822f736df6c.png)

**Comment by jessetabak** [comment]
I now realise it might be because of the SSO redirect, could that be the issue?

**Comment by abhinaba-ghosh** [comment]
@jessetabak yes exactly, if `window` gets reloaded, you need to call `waitForReact()` immediately. So, for your case, its ,

```js
describe('The Home Page', () => {
    before(() => {
        cy.visit('/');
        cy.waitForReact();
    });

    it('shows the header', () => {
        cy.waitForReact();
        cy.react('Header')
            .should('be', 'visible');
    });
});
```

**Comment by jessetabak** [comment]
@abhinaba-ghosh Thanks for the quick response.

For now, the only way I can get it to work is like this:
```js
describe('The Home Page', () => {
    before(() => {
        cy.visit('/');
        cy.wait(5000);
        cy.waitForReact();
    });

    it('shows the header', () => {
        cy.react('Header')
            .should('be.visible');
    });
});
```

I plan to disable the SSO part during testing anyway, so I won't need the cy.wait part anymore.
