### ISSUE TITLE
cy.waitForReact is not a function

### ISSUE THREAD

**Issue by bahachammakhi** [abhinaba-ghosh/cypress-react-selector#117]
Iam just trying this library i followed the steps in the setup guide but it still got this error :
**cy.waitForReact is not a function**

**Note: I am using it with typescript**

![image](https://user-images.githubusercontent.com/44755179/103768972-c68ae180-5023-11eb-9e0c-da1d2b131b19.png)

### my setup :
support/index.js file:
![image](https://user-images.githubusercontent.com/44755179/103769139-08b42300-5024-11eb-85ad-37fddf978467.png)

tsconfig:

```
{
  "extends": "../tsconfig.json",
  "include": ["../node_modules/cypress","../node_modules/cypress-react-selector", "*/*.ts"],
  "compilerOptions": {
    "types": ["node", "cypress", "cypress-react-selector"]
  }
}
```

cypress.json : 

```
{
  "baseUrl": "http://localhost:3000",
  "integrationFolder": "./src/tests/e2e/integration",
  "screenshotsFolder": "./src/tests/e2e/screenshots",
  "supportFile": false,
  "pluginsFile": false,
  "video": false,
  "env": {
    "cypress-react-selector": {
      "root": "#root"
    }
  }
}
```

version : 
    "cypress-react-selector": "^2.2.2",
    "cypress": "^6.2.1",

**Comment by abhinaba-ghosh** [comment]
Hi @bahachammakhi , Thanks for giving this library a try. I am seeing in your `cypress.json` file, you configured `supportFile:false`. can you try removing the line from the configuration. Let me know if that solves the issue.

**Comment by bahachammakhi** [comment]
Thanks, @abhinaba-ghosh, that solves this issue! hope this will help others too, good work

**Comment by abhinaba-ghosh** [comment]
I am glad it worked. In case you want to help the development going, you can [help here](https://www.buymeacoffee.com/abhinabaghosh). This is absolutely optional.

Happy coding!
