### ISSUE TITLE
Feat: Add Cypress options in react commands

### ISSUE THREAD

**Issue by KyorCode** [abhinaba-ghosh/cypress-react-selector#119]
Hi,

I don't know if the Cypress options are fully respected.

`cy.react(
      "MyComponent",
      { props: { name: "testComponent" } },
      { timeout: 20000 }
    ).should("exist");`

The timeout I pass there isn't respected ( that component takes a little while to load due to api calls, 20sec is extreme I know ), but still the cy.react uses the default timeout + 100 sec to check if the component is present.

Could this be looked at?

**Comment by abhinaba-ghosh** [comment]
Hi @KyorCode , Thanks for writing. Cypress options currently not supported in `react` commands. This will be a good addition. Will look into it. Meanwhile, I appreciate any PR coming from the community.

**Comment by abhinaba-ghosh** [comment]
Hi @KyorCode , This is addressed in `v2.3.0`. Feel free to re-open the ticket if the issue still appears. 

you can also pass the `timeout` as a object literal in the react commands like,

```js
cy.react('MyComponent', { options: { timeout: 50000 } });
```

If this library helps your development journey and want to get the improvement going, feel free to [sponsor](https://www.buymeacoffee.com/abhinabaghosh) the project 😄
