### ISSUE TITLE
Inconsistent finding component

### ISSUE THREAD

**Issue by rhugie** [abhinaba-ghosh/cypress-react-selector#122]
I'm using the cy.react function to find a row in a list and select it. if I run it 10 times on the same list and same data, maybe half the time it will find the row and select it, the other half of the time it fails with "cy.click() failed because it requires a DOM element" which I assume means it hasn't found it.  Have tried adding cy.wait() before with different durations but even adding multiple seconds to the wait to make sure it's loaded still have the same issue. Below is an example of the code I'm using. 

I've verified that the name is unique.

cy.react('Link');
cy.react('Link', {props: {name: 'mdRow0'}}).click();

cypress.json
`{
    "chromeWebSecurity": false,
    "viewportWidth": 1500,
    "viewportHeight": 1000,
    "env": {
      "cypress-react-selector": {
        "root": "#root"
      }
    }
}`

![Screen Shot 2021-01-15 at 10 35 41 AM](https://user-images.githubusercontent.com/2208967/104759732-988d5780-571d-11eb-9d66-df9a6ffc1d05.png)

**Comment by abhinaba-ghosh** [comment]
Hi @rhugie , Thanks for raising this concern. Can you provide detailed cypress error logs when it unable to find the element? The library has an inbuilt retry mechanism already, so it will be interesting to see what logs it spits out.

**Comment by abhinaba-ghosh** [comment]
Closing for inactivitry.

Kindly open the ticket if the issue persists in the latest version.
