### ISSUE TITLE
getProps() returns undefiend

### ISSUE THREAD

**Issue by jansedlon** [abhinaba-ghosh/cypress-react-selector#13]
Hello! I'm trying to use function `getProps()` on `GridItem` component which comes from this package [React-grid-layout](https://github.com/STRML/react-grid-layout), however it returns undefined.

My usage looks like this 
```js
cy
        .react('GridItem', { i: 'evaluation' })
        .getProps()
```

**Comment by abhinaba-ghosh** [comment]
Hi @jansedlon ,

According to the [docs](https://github.com/abhinaba-ghosh/cypress-react-selector#get-react-properties-from-element), ```cy.react``` returns the web element, but to get the react properties you need to use ```cy.gerReact```

```js
cy.getReact('GridItem', { i: 'evaluation' }).getProps()
```

Let me know if this helps! Thanks.

**Comment by jansedlon** [comment]
@abhinaba-ghosh Ah, you're right! I'm blind, thank you.

**Comment by abhinaba-ghosh** [comment]
Blind? absolutely not! I think this gives me an opportunity to make the error messages clear. Thanks for pointing out.

**Comment by abhinaba-ghosh** [comment]
Hey, I hope all going well with the plugin. Recently we did some improvements. You can have a look at the new version. 

Now you can choose to [support](patreon.com/user?u=32109749) the project. It is completely optional.
