### ISSUE TITLE
Yarn 2 requires resq to be installed explicitly and unplugged when using cypress-react-selector

### ISSUE THREAD

**Issue by DaveHarlow** [abhinaba-ghosh/cypress-react-selector#132]
There's an easy workaround (in the title) but cypress-react-selector fails when using PnP due to attempting cy.readfile() on resq, due to PnP storing everything as an archive instead of unpacking.

Can be got round via:

yarn add resq -D
yarn unplug resq

But might be worth adding to the readme?

**Comment by abhinaba-ghosh** [comment]
@DaveHarlow Thanks for the input. Appreciate a PR as you have hands-on experience with this.

**Comment by DaveHarlow** [comment]
No worries - I'll add it once I'm off the work VPN, just didn't want to push readme changes without your say so.

**Comment by abhinaba-ghosh** [comment]
> No worries - I'll add it once I'm off the work VPN, just didn't want to push readme changes without your say so.

No issues.

**Comment by francisu** [comment]
See: https://github.com/abhinaba-ghosh/cypress-react-selector/issues/230#issuecomment-1031885793
