### ISSUE TITLE
Running .should() against .getCurrentState() should re-run on fail until timeout

### ISSUE THREAD

**Issue by burke-newell** [abhinaba-ghosh/cypress-react-selector#152]
With the test below I am checking for an animation to be finished.
The `isAnimationFinished` state will become true after 1.5 seconds, but `.getCurrentState()` does not get called/tested again when the assertion fails.
I would expect `.getCurrentState()` to be retried until the timeout period passes.

```
cy.getReact('*', {props: { animationBegin: 0 } })
  .nthNode(0)
  .getCurrentState()
  .should(($state) => {
        expect($state.isAnimationFinished).to.be.true
  });
```
![2021-03-07_12h03_40](https://user-images.githubusercontent.com/69968530/110248056-3db5f680-7f3d-11eb-9ad2-3d7a608259ab.png)
![2021-03-07_12h04_35](https://user-images.githubusercontent.com/69968530/110248070-4c9ca900-7f3d-11eb-8bdb-975faedbb2a2.png)

**Comment by burke-newell** [comment]
@bahmutov suggested https://github.com/bahmutov/cypress-recurse
Which worked great to handle this scenario.

**Comment by abhinaba-ghosh** [comment]
Hi @burke-newell, can you let us know how you are using the code lugin with cypress-react-sepector. Will be helpful for those who fall under the same problem.

**Comment by burke-newell** [comment]
```
import { recurse } from 'cypress-recurse';

recurse(
    () => cy.getReact('*', {props: { animationBegin: 0 } }) 
            .nthNode(0)
            .getCurrentState(),
    (state) => {expect(state.isAnimationFinished).to.be.true}
       )
```
