### ISSUE TITLE
please tell me how to install cypress-react-selector step by step and also how to start this?

### ISSUE THREAD

**Issue by rmrao12** [abhinaba-ghosh/cypress-react-selector#157]
first i installed cypress then this dependency of cypress react selector but i was not able to find tsconfig.json well after that i run cypress by using the command npx cypress open it did open but it is only running those pre defined test cases. well then i tried to copy the calclulator.spec.js in it and tried to run it but it said waitforreact is not a valid command and all other commands as well i just don't get it how to make it work for react app testing. please guide me on how to properly run test for react app because you recommended me to use cypress-react-selector instead of protractor react selector plugin please guide me and help me.

**Comment by abhinaba-ghosh** [comment]
Hi @rmrao12 I suggest you kindly go through the readme step by step by process. If you already followed and having trouble, kindly provide me with the repository, I will help you make the necessary changes. Thanks.
