### ISSUE TITLE
React component in Shadow DOM is not found

### ISSUE THREAD

**Issue by JochenDiekenbrock** [abhinaba-ghosh/cypress-react-selector#158]
I want to test a Web Component that is implemented with React and is using a shadow dom.
The DOM tree (simplified) looks like this:
```
div id="root"
  my-web-component
    div
      #shadow-root
        ...
          MyReactComponent      
```

`cy.waitForReact();` works as expected, so the root id is set correctly and React is loaded.
`cy.react("MyReactComponent");` fails with `Could not find instance of React in given element`

I verified with the React Dev Tools that the React component name is correct. I have specified `"includeShadowDom": true` in cypress.json and cy.get... is able to find elements inside MyReactComponent.

I know that @testing-library/cypress fails finding elements inside Shadow Dom, so my first thought is that this is the problem here as well.

Sorry, I don't have a publicly available test repo currently

**Comment by abhinaba-ghosh** [comment]
Hi @JochenDiekenbrock , sorry for replying late on this. I have tested a couple of scenarios and it seems shadow DOM is well supported. You can check out the example [here](https://github.com/abhinaba-ghosh/cypress-react-selector/tree/master/component/shadow-dom)

Give a chance with the latest version or clone the repo and try the tests locally. Let me know your findings.

**Comment by JochenDiekenbrock** [comment]
Hi @abhinaba-ghosh, I tried it again and created a publicly accessible example: https://github.com/JochenDiekenbrock/lerna-cypress/tree/add-test-with-custom-web-component
My first guess was wrong, the problem is **not** caused by the shadow-root but by the react component being rendered inside a custom web component. Sorry for that!

In my example, please just ignore the lerna stuff, that is used to test another bug. The relevant stuff here is located in the react project `packages/react-app`. 

`packages/react-app/src/App.tsx` renders a HelloWorld React component and <my-web-component>.
my-web-component itself renders another instance of HelloWorld.

`packages/react-app/cypress/integration/app.spec.tsx` tests for the existence of both HelloWorld instances but finds only one.
