### ISSUE TITLE
Components that render `null` cause `Cannot read property 'nodeType' of undefined`

### ISSUE THREAD

**Issue by laurence-myers** [abhinaba-ghosh/cypress-react-selector#19]
This is a rough sketch of a dummy component structure that should demonstrate the issue:

```typescript
const ErrorMessage: React.FC<{ hasError }> = ({ hasError }) => {
  if (hasError) {
    return <p>An error occurred</p>;
  } else {
    return null;
  }
};

function MyForm() {
  return (
    <form>
      <div>
        <input/>
        <ErrorMessage hasError={false}/>
      </div>
      <div>
        <input/>
        <ErrorMessage hasError={false}/>
      </div>
    </form>
  );
}
```

In my Cypress test, I query the error messages like so:
```typescript
cy.react('MyComponent').should('not.be.visible');
```

However, Cypress fails with the error message `TypeError: Cannot read property 'nodeType' of undefined`.

The console log shows `Applied to:  [undefined, undefined]`.

I can see the `ErrorMessage` components in the React Dev Tools, but they have no corresponding node in the DOM.

So, looks like `cypress-react-selector` is finding the component nodes, but pushing `undefined` to the result array.

Should this selector filter out any "undefined" entries from the returned array?

**Comment by abhinaba-ghosh** [comment]
Hi @laurence-myers , if it returns `undefined` what output `Node` information you want to get from the `.react()`?

Can you suggest any sample output structure?

**Comment by laurence-myers** [comment]
Sorry, I'm just learning Cypress, so I'm not really sure how the API should work. 🙁 Maybe I'm using it incorrectly. I was hoping calling `.react('ErrorMessage').should('not.be.visible')` would check for existence of the node, but maybe I should be asserting `.should(not.exist)` or similar? I'll double check if that works.

**Comment by abhinaba-ghosh** [comment]
Thanks @laurence-myers . Let us know if that works.

**Comment by abhinaba-ghosh** [comment]
Hi @laurence-myers , any update you like to share?

**Comment by abhinaba-ghosh** [comment]
closing due to staleness.

**Comment by caseyjhol** [comment]
`.should('not.exist')` doesn't work either. I'm trying to assert that there are 0 AccountCards on the page.

`cy.react("AccountCard").should('not.exist')` throws

> Timed out retrying: Expected to find element: `undefined`, but never found it.

I also tried `cy.react("AccountCard").should("eq", undefined);`, but that returns the same error.

**Comment by caseyjhol** [comment]
After updating to v2.2.1, `cy.react("AccountCard").should("not.exist")` now throws:

![image](https://user-images.githubusercontent.com/2874325/100134152-010a3780-2e45-11eb-9972-354fe1e9ccb4.png)

@abhinaba-ghosh Any ideas for a workaround?

**Comment by abhinaba-ghosh** [comment]
so, the expectation is `AccountCard` should not exist right? I think it's not handled correctly now. Can you raise a ticket explaining the whole scenario?

**Comment by caseyjhol** [comment]
That's correct. I'll get some more info for you and open a new ticket.
