### ISSUE TITLE
cy.react(...) unable to find requested element

### ISSUE THREAD

**Issue by junminleeKS** [abhinaba-ghosh/cypress-react-selector#195]
Hello,
I apologize that I cannot describe exactly why I am having this issue but I been having trouble with `cy.react()` finding the element that I am looking for. 

I have created a demo that reproduces the issue:
https://github.com/junminleeKS/cypress-react-selector-test

The demo contains a test file that can be used by running `cypress open`. By running it as is the tests will fail.

However, in the `App.tsx` file if you change
```
  useEffect(() => {
    setTimeout(() => {
      setAppLoading(false);
    }, 200);
  }, []);
```
to be
```
  useEffect(() => {
    setAppLoading(false);
  }, []);
```
then the tests will work as expected.

**Comment by abhinaba-ghosh** [comment]
@junminleeKS This is interesting. Internally the commands retry up to timeout. It should have handled the asynchronous loading of the components. I will dig deeper.
Can you also check this example : https://github.com/cypress-io/cypress/blob/56234e52d6d1cbd292acdfd5f5d547f0c4706b51/npm/react/cypress/component/advanced/react-book-example/src/components/ProductsList.spec.js#L123

**Comment by jens-duttke** [comment]
I have the same problem. Is there a debug/verbose option, or something similar to see which components `cypress-react-selector` "sees"? Maybe it would make sense to optionally show the component tree, if a component could not be found?

**Comment by jens-duttke** [comment]
I've just figured out that the source of my problem is in the `displayName` handling of the `resq` dependency, and has nothing to do with asynchronous loading of components. I've created a issue in the `resq` issue tracker for that:
https://github.com/baruchvlz/resq/issues/78

**Comment by abhinaba-ghosh** [comment]
Hi @jens-duttke , i think this is handled by https://github.com/abhinaba-ghosh/cypress-react-selector/issues/209
Feel free to reopen the ticket otherwise.
