### ISSUE TITLE
Only add files to the `npm` bundle which are really required.

### ISSUE THREAD

**Issue by jens-duttke** [abhinaba-ghosh/cypress-react-selector#201]
Right now, almost everything is part of the `npm` bundle.
To improve the bundle size, the required disk space and the installation performance it would be good if files/folders like:

- .circleci
- .guthub
- component
- cypress
- .prettierrc
- cypress.json

would be added to the `.npmignore` file.

**Comment by abhinaba-ghosh** [comment]
Hi @jens-duttke Thanks for pointing this out. The folders are ignored at `v2.3.10`
