### ISSUE TITLE
"Component not found" because of not considered `displayName`

### ISSUE THREAD

**Issue by jens-duttke** [abhinaba-ghosh/cypress-react-selector#209]
Previously, the used `resq` dependency did not consider the `displayName` as it's done in the React Dev Tools.
The result was that, it was not possible to find components by their name, if their `name` is minified, even if they had a `displayName`.

I've provided a a fix for that, which has now been merged and released in `resq` version `1.10.1`.

Can you please update `cypress-react-selector` to use the new `resq` version, so that `displayName` is also considered here?

For more information, please see:
baruchvlz/resq#78

**Comment by abhinaba-ghosh** [comment]
Thanks @jens-duttke , it is available in the current version. 
would you mind updating the readme for the `displayName` stuff. It will be really helpful for others.
