### ISSUE TITLE
cy.waitForReact is not a function

### ISSUE THREAD

**Issue by khateeb321** [abhinaba-ghosh/cypress-react-selector#22]
Something missing in the documentation, cannot use any function.
![tempsnip](https://user-images.githubusercontent.com/10035363/89515588-9f5f8800-d7d7-11ea-843f-5301634da4af.png)

**Comment by khateeb321** [comment]
Sorry - it was my fault, I'm using Typescript instead of Javascript, so in addition, to add import 'cypress-react-selector' in command.js we also have to add it in typescript definition file or commands.ts

**Comment by abhinaba-ghosh** [comment]
Hey @khateeb321 , I am glad that you figured that out. If the library works for you, leave a star! Thanks.

**Comment by khateeb321** [comment]
> Hey @khateeb321 , I am glad that you figured that out. If the library works for you, leave a star! Thanks.

Works amazing! I'm impressed
