### ISSUE TITLE
Documentation for cy.waitForReact() incorrect when used with component testing

### ISSUE THREAD

**Issue by francisu** [abhinaba-ghosh/cypress-react-selector#236]
The correct way to use this is simply `cy.waitForReact()` without specifying the `root` argument (including using the `root` env variable). Specifying the `root` as `#app` which is the actual React root in the component testing browser will not work, neither will `#root`.

I don't know why any of this is true, but that's what works, so the documentation should reflect that.

**Comment by abhinaba-ghosh** [comment]
Hi @francisu, appreciate a PR. These are all valuable suggestions.

**Comment by francisu** [comment]
Happy to make a PR, but I don't understand why it's different for component tested applications, and I think that would be helpful to know before I change the doc. And it would also be go to have https://github.com/abhinaba-ghosh/cypress-react-selector/issues/235 resolved first (in case it is actually related to the `waitForReact` config), since this plugin is essentially unusable with component testing now.
