### ISSUE TITLE
Accessing component on minified react app

### ISSUE THREAD

**Issue by ofekudi** [abhinaba-ghosh/cypress-react-selector#238]
Hey.
I'd like to integrate cypress with a React app. Unfortunately, the Create React App build minifies the code, so cypress-react-selector can't recognize component names.
Is there a suggested solution for this?
Thanks

**Comment by maxencelaurent** [comment]
If you had control over the webpack configuration, you could use [webpack-react-component-name](https://www.npmjs.com/package/webpack-react-component-name).

Your problem is `create-react-app` will not let you configure webpack.

**Comment by abhinaba-ghosh** [comment]
Hi @ofekudi , can you please check if these tickets help?
https://github.com/abhinaba-ghosh/cypress-react-selector/issues/209
https://github.com/abhinaba-ghosh/cypress-react-selector/issues/83
