### ISSUE TITLE
waitForReact throws an error when using Webpack

### ISSUE THREAD

**Issue by ajhenry** [abhinaba-ghosh/cypress-react-selector#273]
When using webpack with `require.resolve`, this will return a number rather than a path so this breaks the `waitForReact` function.

Webpack warning when using `require.resolve`: https://webpack.js.org/api/module-methods/#requireresolve
Issue describing that `require.resolve` returns a dependency ID in webpack: https://github.com/webpack/webpack/issues/1554

> Module ID's type can be a number or a string depending on the optimization.moduleIds configuration.

Code that uses `require.resolve`
https://github.com/abhinaba-ghosh/cypress-react-selector/blob/240f5fecee10d0b47d3e17a114df1b46d916e7c1/src/resqInjector.js#L9-L15

Error
```
readFile: 27, utf8, {log: false}

cy.readFile() must be passed a non-empty string as its 1st argument. You passed: 27.
```

Versions
```json
"cypress": "^8.5.0"
"cypress-react-selector": "^2.3.13"
"webpack": "^4",
```

**Comment by abhinaba-ghosh** [comment]
Hi @ajhenry thanks for raising this issue. 
According to this [comment](https://github.com/webpack/webpack/issues/1554#issuecomment-336462319), it seems using `eval` could be a viable solution. Can you give it a try and raise a PR?

**Comment by ajhenry** [comment]
So I tried the solution with `eval` and that returned a weird webpack internal object rather than a path so I'm going to keep investigating
