### ISSUE TITLE
Cannot read properties of undefined (reading 'waitToLoadReact')

### ISSUE THREAD

**Issue by saqrodiliac** [abhinaba-ghosh/cypress-react-selector#302]
I'm trying this library out for the first time by following the cypress.io instructions to get started.  Unfortunately when testing my application (by running cypress) I get the following error message:

![image](https://user-images.githubusercontent.com/31184243/159413052-49434169-2182-40bf-bbbe-00bb56748367.png)

Placing a debugger on that line, I can see that win.resq is undefined making me think the win.eval(script) is not loading the resq library correctly.  I read the discussion https://github.com/abhinaba-ghosh/cypress-react-selector/issues/114 which sounds similar as my page uses SSO however I can't seem to get the library to work using a cy.wait(5000) before the cy.waitForReact() statement.  

![image](https://user-images.githubusercontent.com/31184243/159413437-6de429fb-4fed-46d6-a827-f8ea968cc08f.png)

cypress.json

![image](https://user-images.githubusercontent.com/31184243/159413564-d6eb5e97-367d-4f2c-a929-6891daf48bfe.png)

support/index.js

![image](https://user-images.githubusercontent.com/31184243/159414062-baa686a6-5aa4-4fdc-a6e1-8ab14707a7de.png)

tsconfig.json

![image](https://user-images.githubusercontent.com/31184243/159413729-f9b4fdaa-fd32-4e84-aac1-b7976d3c428e.png)

File versions:

![image](https://user-images.githubusercontent.com/31184243/159413806-c1052dc0-3d12-413c-a1bd-a30715c30bb8.png)

**Comment by abhinaba-ghosh** [comment]
Hi @saqrodiliac thanks for raising the issue. Without the proper visibility, it is difficult for me to reproduce. Is there a way I can reproduce it?

Can you also verify if the `window` object is loaded before we call the `waitForReact`?

**Comment by abhinaba-ghosh** [comment]
Closing for inactivitry.

Kindly open the ticket if the issue persists in the latest version.
