### ISSUE TITLE
How to read all current state of a component?

### ISSUE THREAD

**Issue by khateeb321** [abhinaba-ghosh/cypress-react-selector#31]
I don't know where to ask this question, I think this is the only communication channel.

I want to get the state of the component, without knowing the value, all the examples I have seen is with the value of the state and filtering on the based on that.

Just like getProps
`
cy.getReact('reactComp')
            .getProps('myProp')
            .then((data) => {
                result = data
            })
`

I need the same for state
`
cy.getReact('reactComp')
            .getCurrentState()
            .then((data) => {
                result = data.stateItem
            }) // returns {t: function(){}}
`

**Comment by abhinaba-ghosh** [comment]
Hi @khateeb321, are you looking for something similar?

```js
  cy.getReact('AProduct', { props: { name: 'Second item' } })
        .getCurrentState()
        .should('include', { myName: 'Second item' });
```

**Comment by khateeb321** [comment]
> Hi @khateeb321, are you looking for something similar?
> 
> ```js
>   cy.getReact('AProduct', { props: { name: 'Second item' } })
>         .getCurrentState()
>         .should('include', { myName: 'Second item' });
> ```
> 
> Note: `getCurrentSate` can return any object, not necessarily a JSON.

No, I want to get all the state, I don't know the value of the state, just name.
{ myName: 'Second item' } would not work in my scenario

**Comment by abhinaba-ghosh** [comment]
Can you try the below and let me know the outcome:

```js
cy.getReact('reactComp') .getCurrentState() .then((data) => cy.log(JSON.stringify(data))) 
```

**Comment by khateeb321** [comment]
> Can you try the below and let me know the outcome:
> 
> ```js
> cy.getReact('reactComp') .getCurrentState() .then((data) => cy.log(JSON.stringify(data))) 
> ```

Empty object, by going through React Dev tool, it made me clear that I'm asking for the state in the context of hooks, I believe it is not supported.

**Comment by abhinaba-ghosh** [comment]
Maybe the case. Would you mind creating a sample repo mimicking the scenario (not necessary to have real data)? I can dig deeper and check any feasibility of enhancing the library.

**Comment by abhinaba-ghosh** [comment]
And also check if it really found out the component or not. Make sure the `root` is defined in `cypress.json` file or just do something:

```js
cy.getReact('reactComp', {root:"#root"}) .getCurrentState() .then((data) => cy.log(JSON.stringify(data))) 
```
