### ISSUE TITLE
Installation guide updating/clarification

### ISSUE THREAD

**Issue by Max-Strick** [abhinaba-ghosh/cypress-react-selector#32]
Hello, your plugin looks very suitable for me, but I have trouble with its setup.

### Precondition:
Basic cypress project without any app:
```
.
|  cypress.json
|  package.json
|  package-lock.json
--cypress
|  --integration
|    |  --spec.js
|  --plugins
|    |  --index.js
|  --support
|    |  --index.js
--node_modules
```
### Steps

1. Install resq `npm install --save resq`
2. Install cypress-react-selector `npm i --save cypress-react-selector`
3. Update cypress/support/index.js  by `import 'cypress-react-selector';`
4. Open cypress `npx cypress open`
5. Run spec.js
6. Get error: 
```
C:\..\.\node_modules\cypress-react-selector\index.js:1
import { waitForReact } from './src/resqInjector';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```
7. Install TypeScript `npm install typescript`
8. Create tsconfig.json and insert 
```
{
"compilerOptions": {
"sourceType": "module",
"types": ["node", "cypress", "cypress-react-selector"]
}
}
```
9. The error still occurs 

### Questions
So, can you please tell me what I am doing wrong, what modules should be preinstalled. I have already searched about this issue and I guess it relates to the preprocessor need. 
Taking into account the installation guide may be updated.

**Comment by abhinaba-ghosh** [comment]
Hi @Max-Strick , thanks for raising this concern. Can you let me know which node version you are using?

**Comment by Max-Strick** [comment]
@abhinaba-ghosh , thanks for fast response
v12.16.2

**Comment by abhinaba-ghosh** [comment]
Hi @Max-Strick , Can you try the version V2.0.2. Let me know if upgrading it solves the issue. I have changed the export logic.

**Comment by abhinaba-ghosh** [comment]
I mean cypress-react-selector version 2.0.2

**Comment by Max-Strick** [comment]
@abhinaba-ghosh great! It works!
Thank you for your rapid response and fix.
Also, could you please don't close the issue, tomorrow I will try more thoroughly.
