### ISSUE TITLE
Update plugin to be compatible with Cypress 10

### ISSUE THREAD

**Issue by admah** [abhinaba-ghosh/cypress-react-selector#324]
Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10. 

For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

**Comment by muratkeremozcan** [comment]
Ditto. We had to disable this plugin's commands for cy 10.

**Comment by admah** [comment]
@abhinaba-ghosh I am working on a PR for this now.

**Comment by abhinaba-ghosh** [comment]
Thanks for the awesome work @admah. The cypress 10 support is available in version `v3.0.0`
