### ISSUE TITLE
Incorrect error message?

### ISSUE THREAD

**Issue by gregfenton** [abhinaba-ghosh/cypress-react-selector#4]
At line 22 of https://github.com/abhinaba-ghosh/cypress-react-selector/blob/master/index.js, the error message states:

> React Selector not loaded yet. did you forget to run cy.waitToLoadReact()?

but I believe that as a user of this plugin we are expected to run `cy.waitForReact()`?  It looks like `waitToLoadReact()` is something being called "under the covers", not what a user of the plugin is expected to do?

**Comment by abhinaba-ghosh** [comment]
Hi @gregfenton , thanks for the detailed error description. As a user you need to tell the react selector to wait for react to be loaded for below reason:

1. You might be having a legacy application where react is one of the technology if not only. It is possible that you are loading react views in specific user interaction in that case. So, cypress-react-selector needs to understand at which moment react is loaded. 
2. Sometimes there are multiple react roots available in the application. Let us assume your team is developing different parts of the application as separate react projects and then integrating them all.  In that case Cypress-react-selector needs to understand what is the target react root. 

You will get a better understanding here: https://github.com/abhinaba-ghosh/cypress-react-selector#wait-for-application-to-be-ready-to-run-tests

Also, have a look into the beforeAll method of these sample test: https://github.com/abhinaba-ghosh/cypress-react-selector/blob/master/cypress/integration/react-selector.spec.js

Let me know if it helps. I am open to any suggestions.

**Comment by gregfenton** [comment]
Correct, both those examples show `waitForReact()`, but the error message I indicate says `waitToLoadReact()`.

**Comment by abhinaba-ghosh** [comment]
@gregfenton That's a typo. Good catch! will be fixed in the next version.

**Comment by abhinaba-ghosh** [comment]
Typo is fixed in version V0.1.6

Closing the ticket.
