### ISSUE TITLE
You might want to try Cypress circleci orb

### ISSUE THREAD

**Issue by bahmutov** [abhinaba-ghosh/cypress-react-selector#6]
https://github.com/abhinaba-ghosh/cypress-react-selector/blob/6aed4f9597fab16b6bf48f69aa55158c84855425/.circleci/config.yml#L19

https://github.com/cypress-io/circleci-orb

**Comment by abhinaba-ghosh** [comment]
Hi @bahmutov Thanks for the suggestion.  ORB is integrated here https://github.com/abhinaba-ghosh/cypress-react-selector/pull/7

Appreciate if any feedback for https://github.com/cypress-io/cypress-documentation/pull/2771

Many thanks.
