### ISSUE TITLE
Doesn't limit scope of searching within the parent element scope

### ISSUE THREAD

**Issue by Ankit-Laddha** [abhinaba-ghosh/cypress-react-selector#78]
Not sure if I'm doing something wrong OR it's the accepted behaviour. 

Browser: any
cypress@5.4.0
cypress-react-selector@ = 2.2.0

I'm using mix of .react and .get/.find of cypress while finding any element. There are certain situation when I want to limit the scope of .react() to certain div children. But using .react gives me all the elements on the page instead of the matching one from the scope. 

Pseudo example:

`cy.get('parent-locator')
.react('MyReactComponent')
.click(); `

Error:
`More than one element found for click`

**Comment by abhinaba-ghosh** [comment]
Tracking here https://github.com/abhinaba-ghosh/cypress-react-selector/issues/41
