### ISSUE TITLE
Fluent chained queries doesn't work properly with multiple items

### ISSUE THREAD

**Issue by theKosh** [abhinaba-ghosh/cypress-react-selector#79]
### Summary
Fluent chained queries doesn't work properly with multiple items.

### Precondition
macOS 10.15.7
Chrome 86.0
cypress@5.5.0
cypress-react-selector@ > 2.0.3 (checked on 2.0.4, 2.1.0, 2.2.0).

### Steps to reproduce
1. Have more than one identical element on the page that differs only in the parent element, for example:
`'button', { props: { type: 'submit' } }`.
2. Use the Fluent chained queries syntax to find a specific element through the parent, for example:
```
    cy.react('modal', { hooks: { Context: { modalParams: { type: 'fileCreateModal' } } } })
      .react('button', { props: { type: 'submit' } })
      .click();
```
### Actual result
Cypress error:
> cy.click() can only be called on a single element. Your subject contained 2 elements. Pass { multiple: true } if you want to serially click each element.

The same code works just fine in cypress-react-selector@2.0.3.

### Expected result
The element is clicked, because we filtered out the extra elements by finding the parent element.

**Comment by abhinaba-ghosh** [comment]
Hi @theKosh , we do not allow a propery called `hooks` in the commands. Allowed properties are `props`, `state`, and `exact`. I will throw an error going forward if other properties are passed.

**Comment by theKosh** [comment]
Hi, @abhinaba-ghosh. Why can't we use hooks like in version 2.0.3? Restrictions in a third-party library? It's just very useful in some cases.

**Comment by abhinaba-ghosh** [comment]
version 2.0.3 also does not support the `hooks`. I am not sure how it worked. if you need the support, feel free to open a feature request.
