### ISSUE TITLE
React selector fails on CI

### ISSUE THREAD

**Issue by Ankit-Laddha** [abhinaba-ghosh/cypress-react-selector#83]
### Question:
My tests are working fine on local, but while running on CI the tests fails as soon as they encountered `cy.react` command. Not sure, how and what to debug in this case.

### Env
cypress@5.5.0
cypress-react-selector@ = 2.2.0
CI: Azure

### Error:
` AssertionError: Timed out retrying: Expected to find element: `undefined`, but never found it.
      at Context../node_modules/cypress-react-selector/src/reactHandler.js.exports.react (http://localhost:3000/__cypress/tests?p=cypress/support/index.ts:18089:6)
`

**Comment by abhinaba-ghosh** [comment]
Hi @Ankit-Laddha, Thanks for bringing this.  

sometimes in the production environment React components get minified and changed their names. Kindly inspect the component names and props in production vs beta/stage environments. If components and props adhere to the same nomenclature, then there should be no problem to fetch the elements with react-selector identifiers. In case if you find there are deviations in the production instance, you can build the react app in [profiling mode](https://create-react-app.dev/docs/production-build/#profiling) to have the same component nomenclature. Long story short, if this library working well in the local environment and not in other, that means something got changed in the application under test [AUT].

**Comment by Ankit-Laddha** [comment]
Thanks @abhinaba-ghosh . But if you see the error message , it is trying to find element `undefined` while I'm trying to find component `MyComponent`. Not sure if issue is with minifying of components.
Also, on CI our app is build locally and hence tests are run against that local env instead of dev/staging. In this case, the component name should remain same. 
Please advice.

**Comment by abhinaba-ghosh** [comment]
Can you share the exact `command` you are using?

**Comment by Ankit-Laddha** [comment]
You were correct. The app did have different components name while building on CI. 
But even in that case, should not the error message say: `AssertionError: Timed out retrying: Expected to find element:MyComponent, but never found it` instead of saying it as `undefined`?

**Comment by abhinaba-ghosh** [comment]
Correct. I will push a fix to show a display a meaningful message.

**Comment by abhinaba-ghosh** [comment]
The correct display message is available in `v2.2.1`.

**Comment by caseyjhol** [comment]
I ended up not needing to do anything with `profiling` mode. I created a custom `--ci` flag I can pass when calling build in CI, which minifies everything normally, except it keeps function names and class names untouched. In case this will help anybody in the future:

```js
// webpack.config.js

const pack = Encore.getWebpackConfig();

if (Encore.isProduction() && process.argv.includes("--ci")) {
	let options = {};

	pack.optimization.minimizer.forEach((minimizer) => {
		if (minimizer instanceof TerserPlugin) {
			options = { ...minimizer.options };
			minimizer.options.exclude = ["app"];
		}
	});

	pack.optimization.minimizer.push(
		new TerserPlugin({
			...options,
			include: ["app"],
			terserOptions: {
				...options.terserOptions,
				keep_fnames: true,
				keep_classnames: true,
			},
		})
	);
}
```

**Comment by abhinaba-ghosh** [comment]
hey @caseyjhol , that's a great update. Thanks, mate.
