### ISSUE TITLE
Unclear example of how to select props

### ISSUE THREAD

**Issue by joetidee** [abhinaba-ghosh/cypress-react-selector#86]
In the example in the readme file you have this:
```
// validate the property runtime
cy.getReact('MyTextInput', { props: { field: { name: 'email' } } })
  .getProps('fields.value')
  .should('eq', 'john.doe@cypress.com');
```
but where did `fields.value` come from?

**Comment by abhinaba-ghosh** [comment]
Hi @joetidee, when you try to access a specific prop and if that prop contains a hierarchy then you have to use the dot (.) operator. Please refer to this example repository: https://github.com/gregfenton/example-cypress-react-selector-formik

**Comment by joetidee** [comment]
I guess this is not obvious in the example provided.
