### ISSUE TITLE
TypeScript TypeError require.resolve is not a function

### ISSUE THREAD

**Issue by dmlogs** [abhinaba-ghosh/cypress-react-selector#94]
I just learned of this library and after installing 2.2.1 and adding to an existing test I hit a type error on `require.resolve` in the call `cy.waitForReact(..)`. 

No issue after downgrading to 2.2.0.

**Comment by abhinaba-ghosh** [comment]
@dmlogs can you share the actual error message or the screenshot? 

@nickpalmer may be interested in this as per the recent changes https://github.com/abhinaba-ghosh/cypress-react-selector/pull/90 

CC: @bahmutov

**Comment by abhinaba-ghosh** [comment]
@nickpalmer Can you check whether `2.2.1` build really making a noise for the `require.resolve` ?

**Comment by raymiS** [comment]
@abhinaba-ghosh hello, I've been having the same error when I tried to `import "cypress-react-selector";` and then do a 

`beforeEach(() => {
  cy.waitForReact();
  ...
});`

inside `support/index.js` 

![Screen Shot 2020-11-24 at 3 36 35 PM](https://user-images.githubusercontent.com/31042933/100148756-2d38af00-2e6b-11eb-9584-7cd948781958.png)

**Comment by dmlogs** [comment]
@abhinaba-ghosh - sorry, I didn't include because it doesn't provide much additional context to what I put in the ticket, happy to provide additional info as well 👍 

<img width="802" alt="require-resolve-is-not-a-function" src="https://user-images.githubusercontent.com/680988/100164322-76d5c980-2e6c-11eb-837b-375cf6d21139.png">

**Comment by abhinaba-ghosh** [comment]
@bahmutov any thoughts here?

**Comment by abhinaba-ghosh** [comment]
By looking into [this](https://github.com/abhinaba-ghosh/cypress-react-selector/issues/100), it seems the problem is really happening for a subset of users. Can be a system configuration issue.

**Comment by maga-polito** [comment]
Hi, If it helps it's happening to me too, only when running my project on docker

**Comment by maga-polito** [comment]
Recent [PR](https://github.com/abhinaba-ghosh/cypress-react-selector/pull/90) breaks the selector on MAC and linux, had to go back to version 2.2.0. to fix it.

**Comment by dmlogs** [comment]
I'm not an expert JS developer so take what I say with a grain of salt

Something like below might work to resolve, although I would still be hesitant to tap in to the node_modules folder by path name 

```
const file = require ? require.resolve('resq') : 'node_modules/resq/dist/index.js';
```

Side Note: I've actually moved away from my previous use case for leveraging cypress-react-selector in favor of a simpler mechanism for the behavior I was looking to test that does not require tapping in to the React DOM - otherwise I'd implement and test the above myself, but hopefully someone else can pick it up

**Comment by 0xIslamTaha** [comment]
@abhinaba-ghosh I can confirm it occurs with me too. I'm using Ubuntu 20.01 and Cypress 4.12.0. I had to install V 2.2.0 to solve it. 
![image](https://user-images.githubusercontent.com/17981089/105512747-ccdeb600-5cd1-11eb-80ef-c1405fc9ec5a.png)

**Comment by abhinaba-ghosh** [comment]
@0xIslamTaha is it also happening with the latest version of cypress-react-selector? Can you confirm?

**Comment by nickpalmer** [comment]
require.resolve was add in node version v0.3.0:
https://nodejs.org/api/modules.html#modules_require_resolve_request_options

The only reason I can think that it would not exist is that you are running on a very old version of node.

That said we have moved away from cypress-react-selector, but the code suggested by @dmlogs above should work in versions of node missing require.resolve.

**Comment by abhinaba-ghosh** [comment]
Thanks @nickpalmer and @dmlogs , the suggested code is deployed to `v2.3.4`

**Comment by 0xIslamTaha** [comment]
> require.resolve was add in node version v0.3.0:
> https://nodejs.org/api/modules.html#modules_require_resolve_request_options
> 
> The only reason I can think that it would not exist is that you are running on a very old version of node.
> 
> That said we have moved away from cypress-react-selector, but the code suggested by @dmlogs above should work in versions of node missing require.resolve.

@nickpalmer here is my running node 
```
$ node -v
v14.15.1
```

**Comment by 0xIslamTaha** [comment]
> Thanks @nickpalmer and @dmlogs , the suggested code is deployed to `v2.3.4`

Thanks man, 2.3.4 is working fine.

**Comment by nickpalmer** [comment]
We don't use typescript but apparently it uses a custom implementation of resolution. Telling it to use Node's version via `--moduleResolution node` _might_ fix it but v2.3.4 should work in both situations.

TypeScript's replacement is breaking Node's API contract of offering require.resolve and they really should add a .resolve to their implementation so as not to break the API Node offers.

See:
https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by nickpalmer** [comment]
Issue filed with TypeScript so hopefully they will stop breaking the Node API at some point with their override.

**Comment by abhinaba-ghosh** [comment]
Great input @nickpalmer . Thanks for letting us know.

**Comment by gshrimpling67** [comment]
The implemented fix breaks my setup with the same syntax problem as #128. I have made this hack to get running (although I could just call require.resolve without testing it since the property does exist).

`const file = require.hasOwnProperty('resolve') ? require.resolve('resq') : 'node_modules/resq/dist/index.js';`

node v14.15.4, cypress-react-selector v2.3.4, typescript v4.1.3 in my project. On Windows.

**Comment by abhinaba-ghosh** [comment]
Hi @gshrimpling67, a patch release is made `v.2.3.5`. Let me know if that solves the issue for your case.
