### ISSUE TITLE
Tests failing in GitLab CI

### ISSUE THREAD

**Issue by caseyjhol** [abhinaba-ghosh/cypress-react-selector#95]
Any tests that depend on `cypress-react-selector` consistently fail in GitLab CI. A simple test that passes locally but fails in CI is:
```js
describe("Header", () => {
	beforeEach(() => {
		cy.waitForReact();
	});

	it("is visible", () => {
		cy.react("DashboardHeader").should("be.visible");
	});
});
```

Selecting by element ID works as expected. I've tried using Chromium instead of Electron in CI and that had no effect. I consistently get the following error:
> Timed out retrying; Expected to find element: `undefined`, but never found it.

![image](https://user-images.githubusercontent.com/2874325/100131818-c4890c80-2e41-11eb-9a6d-aa4c20908b69.png)

**Comment by abhinaba-ghosh** [comment]
Hi @caseyjhol Can you refer https://github.com/abhinaba-ghosh/cypress-react-selector/issues/83? Let me know if this helps dig down the issue a bit.

**Comment by caseyjhol** [comment]
Apologies for not seeing that beforehand. It looks like the same issue, so I'll close this and post any updates in that thread.
