### ISSUE TITLE
Non-existent components fail should("not.exist") assertions

### ISSUE THREAD

**Issue by caseyjhol** [abhinaba-ghosh/cypress-react-selector#96]
- cypress-react-selector v2.2.1

I'm trying to assert that there are 0 AccountCards on the page.

`cy.react("AccountCard").should("not.exist")` throws:

> Component not found **\<AccountCard\>**

![image](https://user-images.githubusercontent.com/2874325/100135844-70812680-2e47-11eb-8a23-01dbbcbad034.png)

So, it's correct - the component is not found. However, I would expect for the assertion to pass, not fail.

`cy.react("AccountCard").should("have.length", 0);` runs into a similar issue.

**Comment by abhinaba-ghosh** [comment]
Thanks for raising this. Will look over the weekend. Appreciate a PR to fix this.

**Comment by abhinaba-ghosh** [comment]
Hi @caseyjhol , the fix is avialble in `v2.2.2`. Let me know if you get any hiccups.

**Comment by caseyjhol** [comment]
Awesome - thanks! I'll try this out and let you know how it goes.

**Comment by caseyjhol** [comment]
Gave this a try and it seems to be fixed - thanks again!

**Comment by abhinaba-ghosh** [comment]
Thanks @caseyjhol. Good to know.

If this library helping you in your development journey, you can optionally choose to [sponsor](https://www.patreon.com/user?u=32109749)/ [support](https://www.paypal.com/paypalme/abhinabaghosh) ❤️ .
